### ISSUE TITLE
cypress-slack-reporter requires peer even though it is installed

### ISSUE THREAD

**Issue by deane187** [YOU54F/cypress-slack-reporter#100]
Hi  @YOU54F

Theres a warning for cypress-slack-reporter: 
```
npm WARN cypress-slack-reporter@0.3.1 requires a peer of mochawesome@^3.1.1 but none is installed. You must install peer dependencies yourself.
```
I created an issue [here](https://github.com/Antontelesh/mochawesome-merge/issues/15) too.

**Comment by YOU54F** [comment]
Hey bud! Yeah I spotted that earlier today when I was testing the changes in mochawesome-merge. For now, you should be able to ignore but I’ll get a new version pushed up that loosens the peer dependency requirement.

Thank you for letting me know!

**Comment by deane187** [comment]
Thank you @YOU54F. Appreciate the effort.

**Comment by YOU54F** [comment]
@deane187 

should be sorted in #103 

I've tested in one of my other projects against the branch with 

```
    "cypress-slack-reporter": "YOU54F/cypress-slack-reporter#correctPeerDeps",
```

and now no longer gives a warning.

I will merge it and release a new version once the CI run has passed, thank you for the heads up!

**Comment by YOU54F** [comment]
`v0.4.0` is going through the release pipeline now so should be available in 5 minutes or so

**Comment by deane187** [comment]
Issue resolved!!! Thank you @YOU54F

**Comment by deane187** [comment]
Would you be able to please glance at my circleCi yml and guide as to where i need to add the following steps:
```
combine-reports:
	npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json

generate-report:
	npx marge mochareports/report.json -f report -o mochareports

slack-alert:
	npx cypress-slack-reporter --logger
```
Config.yml:
```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0

workflows:
  build:
    jobs:
      - cypress/run:
          command: "npm run report" Tests run here
          store_artifacts: true
          post-steps:
            - store_artifacts:
                path: mochawesome-report
            - store_test_results:
                path: cypress/results

  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - add-cypress
    jobs:
      - cypress/run:
          command: "npm run report" Tests run here
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: cypress/reports
            - store_artifacts:
                path: mochareports
            - store_artifacts:
                path: mochawesome-report
            - store_test_results:
                path: cypress/results
```

**Comment by YOU54F** [comment]
Awesome, glad thats sorted. 

I've not tried it with orb yet but you will need commands after you have run cypress (and therefore generated your multiple mochawesome reports). Cypress circle ci docs state you can run a custom command [here](https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#custom-command)

Should be something like this after your jobs that run the tests

```
      - cypress/run:
          command: npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report-$$(date +'%Y%m%d-%H%M%S').json

      - cypress/run:
          command: npx marge mochareports/*.json -f report-$$(date +'%Y%m%d-%H%M%S') -o mochareports

      - cypress/run:
          command: npx cypress-slack-reporter --logger
```

**Comment by deane187** [comment]
You the best man.

Thanks again.

CPT.
South Africa.

**Comment by YOU54F** [comment]
no worries chap, i've just created a repo to test out your config so I'll keep you posted

https://github.com/YOU54F/cypress-circleorbtest

**Comment by YOU54F** [comment]
sorted @deane187, got it working with the orb :) although I think it needs a`when: always` in the steps for the reporting, so it reports when the cypress run fails

see ci run here = https://circleci.com/gh/YOU54F/cypress-circleorbtest/11
and the repo here = https://github.com/YOU54F/cypress-circleorbtest

circleci config

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0

workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - run: npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json
            - run: npx marge mochareports/*.json -f report -o mochareports
            - run: npx cypress-slack-reporter --logger
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/reports
          
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - add-cypress
    jobs:
      - cypress/run:
          post-steps:
            - run: npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json
            - run: npx marge mochareports/*.json -f report -o mochareports
            - run: npx cypress-slack-reporter --logger
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/results
```
