### ISSUE TITLE
Slack message shows as passed(green) when CircleCi job fails

### ISSUE THREAD

**Issue by deane187** [YOU54F/cypress-slack-reporter#966]
When a nightly run is executed I want it to send a slack message on failure only, which does work but the message on slack is incorrect. I see the bellow on failed builds:
**Slack Message**
<img width="643" alt="Screenshot 2021-02-17 at 14 04 58" src="https://user-images.githubusercontent.com/27348820/108202200-6cecfb00-7129-11eb-8b51-a9c19c6adefe.png">

**CircleCi**
<img width="1054" alt="Screenshot 2021-02-17 at 14 11 18" src="https://user-images.githubusercontent.com/27348820/108202992-93f7fc80-712a-11eb-9acc-92ef7ad94670.png">

**.yml config**
```
nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          no-workspace: true
          name: Run All Tests
          parallelism: 2
          group: Nightly
          command: node cypress-retries.js Nightly
          post-steps:
            - run:
                when: always
                name: Merge MochaAwesome Reports
                command: npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json
            - run:
                when: always
                name: Create mochawesome html report
                command: npx marge mochareports/*.json -f report -o mochareports
            - run:
                when: on_fail
                name: Slack report
                command: npx cypress-slack-reporter --verbose
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/reports
            - store_artifacts:
                path: cypress/videos/e2e
            - store_artifacts:
                path: cypress/screenshots/e2e
```
