### ISSUE TITLE
Support for github actions

### ISSUE THREAD

**Issue by vrknetha** [YOU54F/cypress-slack-reporter#980]
Send the message support for Github actions and bitbucket pipelines

**Comment by heidi-patrick** [comment]
+1 would be great

**Comment by YOU54F** [comment]
Hey @vrknetha @heidi-patrick 

Sounds like a good idea, I've not had a play with github actions yet, happy for contributions

**Comment by bennymeade** [comment]
I would love github actions. I did test it just to see what happens:
```
- name: Slack notification with total pass/fail
        if: always()
        run: |
          npx cypress-slack-reporter --report-dir mochawesome-report --ci-provider none
```
and `SLACK_WEBHOOK_URL` set in GitHub secrets.

Erroring I guess because it cannot fetch the webhook URL:
```
(node:901) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'split' of undefined
    at Object.exports.slackRunner (/__w/cypress-reporting-gh-pages/cypress-reporting-gh-pages/node_modules/cypress-slack-reporter/bin/slack/slack-alert.js:167:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by YOU54F** [comment]
weird, could you try echoing it out on a step, you might need to export it in your ci runner like

`export SLACK_WEBHOOK_URL = ${{ secrets.SLACK_WEBHOOK_TEST_AUTOMATION }}` ?

**Comment by bennymeade** [comment]
Bravo, that worked : )
![image](https://user-images.githubusercontent.com/1033474/117861436-ba44b880-b291-11eb-99fd-8da0ca459256.png)

**Comment by bennymeade** [comment]
Yes definitely, I'm happy to do that @YOU54F Thanks again for your speedy responses.

**Comment by bennymeade** [comment]
Here's my GH workflow for others benefit:

```
name: Cypress Slack notify
on:
  workflow_dispatch:

jobs:
  cypress-test:
    name: Run on Chrome 89
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - uses: actions/checkout@v2

      - name: Install Cypress with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Slack notification with cypress-slack-reporter
        if: always()
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          npx cypress-slack-reporter --report-dir mochawesome-report --ci-provider none
```
